import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useAtom } from 'jotai'
import { testAtom } from '../store'
import clsx from 'clsx'
import Test from '../components/Test'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [{ darkmode }, setTest] = useAtom(testAtom)
  return (
    <div className={clsx('flex min-h-screen flex-col', inter.className)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container py-10">
        <div className="mb-10 flex items-center gap-3">
          <button
            className="button"
            onClick={() =>
              setTest((prevState) => ({
                ...prevState,
                darkmode: !prevState.darkmode,
              }))
            }
          >
            Toggle Global Theme
          </button>
          <p>state: {darkmode ? 'dark' : 'light'}</p>
        </div>
        <Test />
      </main>
      <footer className="mt-auto flex justify-center gap-3">
        <p>hello</p>
        <p>hello</p>
        <p>hello</p>
        <p>hello</p>
      </footer>
    </div>
  )
}
